language: python

python:
  - "3.6"

env:
  - GPYTORCH_VERSION=stable
  - GPYTORCH_VERSION=master

install:
  - pip install cython numpy scipy pytest
  - if [[ $GPYTORCH_VERSION = "stable" ]]; then
      pip install gpytorch;  # has pytorch as a dependency
    else
      pip install torch_nightly -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html;
      pip install git+https://github.com/cornellius-gp/gpytorch.git;
    fi
  - pip install -e .;

script:
  - python -c "import gpytorch; print(f'GPyTorch version: {gpytorch.__version__}')"
  - pytest -ra

matrix:
  include:
    - env: LINT_CHECK
      install: pip install black
      script: black --check --diff .
