language: python

python:
  - "3.6"

matrix:
  include:
    # Stable versions under py3.6
    - name: "GPyTorch + PyTorch stable (Python 3.6)"
      python: "3.6"
      install:
        - pip install -q cython numpy
        # TODO: Remove when locked to upcoming GPyTorch release 0.3.2
        - pip install -q git+https://github.com/cornellius-gp/gpytorch.git@8f0d338d42222689f0106f5f29e62ef4777a392f
        - pip install -q -e .[test]
      script:
        - pytest -ra --cov=. --cov-report term-missing
    # Stable versions under py3.7
    - name: "GPyTorch + PyTorch stable (Python 3.7)"
      # Enable Python 3.7 w/o without globally enabling sudo and xenial dist
      # See https://github.com/travis-ci/travis-ci/issues/9815
      python: "3.7"
      dist: xenial
      install:
        - pip install -q cython numpy
        # TODO: Remove when locked to upcoming GPyTorch release 0.3.2
        - pip install -q git+https://github.com/cornellius-gp/gpytorch.git@8f0d338d42222689f0106f5f29e62ef4777a392f
        - pip install -q -e .[test]
      script:
        - pytest -ra --cov=. --cov-report term-missing
    # Latest versions
    - name: "GPyTorch + PyTorch latest"
      python: "3.6"
      install:
        - pip install -q cython numpy
        - pip install -q torch_nightly -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html;
        - pip install -q git+https://github.com/cornellius-gp/gpytorch.git
        - pip install -q -e .[test]
      script:
        - pytest -ra --cov=. --cov-report term-missing
    # Flake8 linting
    - name: "Lint: flake8 (Python 3.6)"
      python: "3.6"
      install:
        - pip install -q flake8
      script:
        # don't use .flake8 config for now, since don't need custom plugin
        - flake8 --isolated --ignore=T484,T499,W503,E704,E231,E203 --max-line-length=88
    # Black linting for codestyle enforcement
    - name: "Lint: black (Python 3.6)"
      python: "3.6"
      install:
        - pip install -q black
      script:
        - black --check --diff .
    # Build sphinx docs
    - name: "Docs: Sphinx (Python 3.6)"
      python: "3.6"
      install:
        - pip install -q cython numpy
        # TODO: Remove when locked to upcoming GPyTorch release 0.3.2
        - pip install -q git+https://github.com/cornellius-gp/gpytorch.git@8f0d338d42222689f0106f5f29e62ef4777a392f
        - pip install -q -e .[dev]
      script:
        # warnings treated as errors
        - sphinx-build -WT --keep-going sphinx/source sphinx/build
