language: python

python:
  - "3.6"

env:
  # - GPYTORCH_VERSION=stable  # TODO: add back in when locked to a release
  - GPYTORCH_VERSION=master

install:
  - pip install cython numpy scipy pytest black sphinx sphinx_autodoc_typehints
  - if [[ $GPYTORCH_VERSION = "stable" ]]; then
      pip install -q gpytorch;
    else
      pip install -q torch_nightly -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html;
      pip install -q git+https://github.com/cornellius-gp/gpytorch.git;
    fi
  - pip install -q -e .

script:
  - black --check --diff .
  - python -c "import gpytorch; print('Testing with GPyTorch Version:' + ' ' +  gpytorch.__version__)"
  - pytest -ra
  - sphinx-build -T sphinx/source sphinx/build
