version: 2


aliases:

  - &exclude_ghpages_fbconfig
    branches:
      ignore:
        - gh-pages
        - fb-config

  - &install_test_docs_pip
    steps:
      - checkout
      - run:
          name: install deps via pip
          command: ./scripts/install_via_pip.sh
      - run:
          name: lint black
          command: |
            source ../env/bin/activate
            black --check --diff .
      - run:
          name: lint flake8
          command: |
            source ../env/bin/activate
            flake8
      - run:
          name: unit tests
          command: |
            source ../env/bin/activate
            pytest -ra --cov=. --cov-report term-missing
      - run:
          name: build sphinx docs
          command: |
            source ../env/bin/activate
            sphinx-build -WT --keep-going sphinx/source sphinx/build

  - &install_test_docs_conda
    steps:
      - checkout
      - run:
          name: install deps via conda
          command: ./scripts/install_via_conda.sh -l
      - run:
          name: lint black
          command: black --check --diff .
      - run:
          name: lint flake8
          command: flake8
      - run:
          name: unit tests
          command: pytest -ra --cov=. --cov-report term-missing
      - run:
          name: build sphinx docs
          command: sphinx-build -WT --keep-going sphinx/source sphinx/build

  - &auto_deploy_site
    steps:
      - checkout
      - run:
          name: install deps via pip
          command: ./scripts/install_via_pip.sh
      - run:
          name: deploy to GitHub Pages
          command: |
            source ../env/bin/activate
            git config --global user.email "botorchnik@users.noreply.github.com"
            git config --global user.name "botorchnik"
            cd website
            yarn install
            #echo "machine github.com login botorchnik password $GITHUB_TOKEN" > ~/.netrc
            #GIT_USER=botorchnik USE_SSH=true yarn run publish-gh-pages

jobs:
  lint_test_py36_pip:
    docker:
      - image: circleci/python:3.6.8
    <<: *install_test_docs_pip
  lint_test_py37_conda_latest:
    docker:
      - image: continuumio/miniconda3
    <<: *install_test_docs_conda
  auto_deploy_site:
    docker:
      - image: circleci/python:3.6.8-node
    <<: *auto_deploy_site

workflows:
  version: 2
  lint_and_test:
    jobs:
      - lint_test_py36_pip:
          filters: *exclude_ghpages_fbconfig
      - lint_test_py37_conda_latest:
          filters: *exclude_ghpages_fbconfig
  # auto_deploy_site:
  #   jobs:
  #     - auto_deploy_site:
  #         filters:
  #           branches:
  #             only:
  #               - master
