#!/bin/bash
# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

name: Tutorials

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:


jobs:
  run_tutorials_with_smoke_test:
    name: Run tutorials with smoke test on latest PyTorch / GPyTorch / Ax
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Run tutorials and upload csv
      run: |
        touch test_file0.csv
        git checkout artifacts
        git add test_file0.csv
        git commit test_file0.csv -m "Adding most recent tutorials output"
        git push origin artifacts
